apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodhub-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodhub-frontend
  template:
    metadata:
      labels:
        app: foodhub-frontend
    spec:
      containers:
      - name: frontend
        image: yourdockerhubusername/foodhub-frontend:latest
        ports:
        - containerPort: 80
  